apiVersion: v1
kind: Template
labels:
  template: kibana-persistent-template
message: |-
  The following service(s) have been created in your project: ${KIBANA_SERVICE_NAME}.

   Connection URL: http://${KIBANA_SERVICE_NAME}:5601/
metadata:
  annotations:
    description: |-
      Kibana service, with persistent storage.

      NOTE: You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-kibana
    openshift.io/display-name: Kibana (Persistent)
    tags: kibana,elasticsearch
    template.openshift.io/documentation-url: https://www.elastic.co/guide/en/kibana/5.6/index.html
    template.openshift.io/long-description: This template provides a standalone Kibana
      application.
    template.openshift.io/provider-display-name: SDP Team
    template.openshift.io/support-url: https://svcmgr.cdc.gov/
  creationTimestamp: null
  name: kibana-persistent
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${KIBANA_SERVICE_NAME}
  spec:
    ports:
    - name: restapi
      protocol: TCP
      port: 5601
      targetPort: 5601
    selector:
      name: ${KIBANA_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${KIBANA_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${KIBANA_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${KIBANA_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${KIBANA_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: ELASTICSEARCH_URL
            value: ${ELASTICSEARCH_URL}
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
              httpGet:
                path: /
                port: 5601
                scheme: HTTP
              initialDelaySeconds: 240
              timeoutSeconds: 10
              periodSeconds: 60
              successThreshold: 1
              failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /
                port: 5601
                scheme: HTTP
              initialDelaySeconds: 240
              timeoutSeconds: 10
              periodSeconds: 30
              successThreshold: 1
              failureThreshold: 5
          name: kibana
          ports:
          - containerPort: 5601
            protocol: TCP
          resources:
            requests:
              memory: ${MEMORY_LIMIT}i
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /usr/share/kibana/data
            name: ${KIBANA_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: ${KIBANA_SERVICE_NAME}-data
          persistentVolumeClaim:
            claimName: ${KIBANA_SERVICE_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - kibana
        from:
          kind: ImageStreamTag
          name: ${KIBANA_IMAGE}:${KIBANA_VERSION}
          namespace: ${NAMESPACE}
        lastTriggerImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512M
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for this instance.
  displayName: Kibana Service Name
  name: KIBANA_SERVICE_NAME
  required: true
  value: kibana
- description: The name of the Kibana imagestream to be used.
  displayName: Kibana Image Name
  name: KIBANA_IMAGE
  value: ocp-kibana
- description: Version of Kibana image to be used (5.6, 5.6.2, or latest); this should match the version number for the ElasticSearch instance used
  displayName: Version of Kibana Image
  name: KIBANA_VERSION
  required: true
  value: "5.6"
- description: The URL of the Elasticsearch instance to use for all your queries
  displayName: ElasticSearch URL
  name: ELASTICSEARCH_URL
  value: http://elasticsearch:9200
  required: true
- description: Volume space available for configs, e.g. 256Mi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 256Mi
